[package]
name = "HelixWave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.4.2"
thiserror = "1.0.48"
url = "2.4.1"
